# Generated by Django 3.2.8 on 2021-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='bookingtime',
            field=models.DateTimeField(default='9999-01-01 00:00'),
        ),
    ]
