# Generated by Django 3.2.8 on 2021-10-28 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_advisor_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='bookingtime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), size=None),
        ),
    ]
