# Generated by Django 3.2.8 on 2021-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp',
            new_name='advisor',
        ),
    ]
