# Generated by Django 3.2.8 on 2021-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_advisor_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.BooleanField(default=False),
        ),
    ]
