# Generated by Django 3.2.8 on 2021-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20211028_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='bookingtime',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
