# Generated by Django 3.2.8 on 2021-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_advisor_bookingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='booking_id',
            field=models.IntegerField(null=True),
        ),
    ]
